#!/usr/bin/env python3
"""V4.0-beta 1 floorplan helper.

manifest : read spatial_scene_graph.json and write render_manifest.yaml, the
           list of base/overlay images that must be rendered per floor.
build    : write floorplan_v4/floor_<n>f.yaml (one picture-elements card per
           floor, loaded from new-ui.yaml with !include). Uses the real render
           from www/floorplan/v4/<floor>/ when present, otherwise the
           placeholder SVG in www/floorplan/3d/.

Colour overlays are rendered with a pure red light (hs 0,100) at full
brightness. card_mod then applies hue-rotate(h) saturate(s) and opacity
(brightness/255) from the light's attributes.
"""
import json
import math
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
GRAPH = ROOT / "spatial_scene_graph.json"
MANIFEST = ROOT / "render_manifest.yaml"
COORDS = ROOT / "www/floorplan/3d/floorplan_3d_coordinates.json"
OUT_DIR = ROOT / "floorplan_v4"
FLOOR_OPTION = {
    "1f": "1F 車庫",
    "2f": "2F 客廳餐廳",
    "3f": "3F 主臥室",
    "4f": "4F 次臥",
    "5f": "5F 頂樓",
}

# switch.* entities that are lamps (name ends in "deng") but not plugs/sockets
LAMP_SWITCH = re.compile(r"deng(_\d+)?$")


def is_light(e):
    eid = e["entity_id"]
    if e["domain"] == "light":
        return True
    return e["domain"] == "switch" and bool(LAMP_SWITCH.search(eid.split(".", 1)[1]))


def manifest():
    graph = json.loads(GRAPH.read_text())
    out = [
        "# V4.0-beta 1 render manifest (generated by scripts/generate_floorplan_v4.py)",
        "# Per floor: render one base image (all lights off) and one image per light",
        "# (only that light on). Same camera, same size, same framing for every image.",
        "# Recommended size: 1600x1000 WebP/PNG. Put files in www/floorplan/v4/<floor>/.",
        "floors:",
    ]
    for key, fl in graph["floors"].items():
        f = key.lower()
        out += [
            f"  {f}:",
            f"    name: \"{fl['name']}\"",
            f"    base: www/floorplan/v4/{f}/base.webp",
            "    lights:",
        ]
        for e in fl["entities"]:
            if not is_light(e):
                continue
            eid = e["entity_id"]
            kind = "color" if e["domain"] == "light" else "onoff"
            name = eid.split(".", 1)[1]
            out += [
                f"      - entity: {eid}",
                f"        room: \"{e['room']}\"",
                f"        mode: {kind}   # color = hue/brightness sync, onoff = on/off overlay",
                f"        image: www/floorplan/v4/{f}/{name}.webp",
                f"        pos_2d: [{e['coordinates']['x']}, {e['coordinates']['y']}]",
            ]
    MANIFEST.write_text("\n".join(out) + "\n")
    n = sum(1 for fl in graph["floors"].values() for e in fl["entities"] if is_light(e))
    print(f"wrote {MANIFEST} ({n} light overlays + {len(graph['floors'])} base images)")


TOGGLE = {"light", "switch", "fan", "cover"}
ICONS = {
    "light": "mdi:lightbulb", "switch": "mdi:light-switch", "fan": "mdi:fan",
    "cover": "mdi:garage", "lock": "mdi:lock", "climate": "mdi:air-conditioner",
    "camera": "mdi:cctv", "binary_sensor": "mdi:motion-sensor",
}


def overlay_style(mode):
    if mode == "color":
        return (
            "{% set on = is_state(config.entity, 'on') %}\n"
            "{% set b = state_attr(config.entity, 'brightness') | default(255, true) %}\n"
            "{% set hs = state_attr(config.entity, 'hs_color') | default([0, 0], true) %}\n"
            ":host {\n"
            "  opacity: {{ (b / 255) if on else 0 }} !important;\n"
            "  filter: hue-rotate({{ hs[0] }}deg) saturate({{ hs[1] / 100 }});\n"
            "  mix-blend-mode: lighten;\n"
            "  pointer-events: none;\n"
            "  transition: opacity .4s;\n"
            "}\n"
        )
    return (
        ":host {\n"
        "  opacity: {{ 1 if is_state(config.entity, 'on') else 0 }} !important;\n"
        "  mix-blend-mode: lighten;\n"
        "  pointer-events: none;\n"
        "  transition: opacity .4s;\n"
        "}\n"
    )


def build_floor(key, fl, coords, manifest_lights):
    f = key.lower()
    real_dir = ROOT / "www/floorplan/v4" / f
    base_real = next((p for p in (real_dir / "base.webp", real_dir / "base.png") if p.exists()), None)
    base = f"/local/floorplan/v4/{f}/{base_real.name}" if base_real else f"/local/floorplan/3d/floor_{f}_3d.svg?v=2"
    pos = coords.get(key, {}).get("entities", {})
    elements = []
    # overlays first, so hotspots stay on top
    for lt in manifest_lights:
        img = real_dir / Path(lt["image"]).name
        if not img.exists():
            continue
        elements.append({
            "type": "image", "entity": lt["entity"],
            "image": f"/local/floorplan/v4/{f}/{img.name}",
            "tap_action": {"action": "none"},
            "style": {"top": "50%", "left": "50%", "width": "100%"},
            "card_mod": {"style": overlay_style(lt["mode"])},
        })
    for e in fl["entities"]:
        eid, dom = e["entity_id"], e["domain"]
        lt = next((x for x in manifest_lights if x["entity"] == eid), None)
        p = None
        if lt and lt.get("pos_pct"):
            p = {"pct_left": lt["pos_pct"][0], "pct_top": lt["pos_pct"][1]}
        p = p or pos.get(eid)
        if not p:
            continue
        style = {"left": f"{p['pct_left']}%", "top": f"{p['pct_top']}%"}
        if dom == "sensor" and ("temperature" in eid or "wen_du" in eid):
            elements.append({
                "type": "state-label", "entity": eid, "suffix": "°C",
                "style": {**style, "color": "#ff5252", "font-size": "13px", "font-weight": "700",
                          "text-shadow": "0 0 3px #000, 0 0 6px #000"},
            })
        elif dom in TOGGLE or dom in ("lock", "climate", "camera") or (
            dom == "binary_sensor" and re.search(r"motion|person", eid)
        ):
            plug = dom == "switch" and not is_light(e)
            el = {
                "type": "state-icon", "entity": eid, "state_color": True,
                "icon": "mdi:power-socket-eu" if plug else ICONS.get(dom),
                "style": {**style, "--mdc-icon-size": "20px", "color": "#fff",
                          "width": "30px", "height": "30px", "display": "flex",
                          "align-items": "center", "justify-content": "center",
                          "box-sizing": "border-box", "background": "rgba(30,30,30,.72)",
                          "border": "1px solid rgba(255,255,255,.55)", "border-radius": "50%"},
                "tap_action": {"action": "toggle"} if dom in TOGGLE else {"action": "more-info"},
                "hold_action": {"action": "more-info"},
            }
            elements.append(el)
    return {"type": "picture-elements", "image": base, "elements": elements}


def build_controls(key, fl):
    """Per-floor room-control grid (button-card iOS templates), shown under the map."""
    seen, cards = set(), []
    for e in fl["entities"]:
        eid, dom = e["entity_id"], e["domain"]
        if eid in seen or dom not in ("light", "switch", "cover", "lock", "fan", "climate"):
            continue
        seen.add(eid)
        tpl = {"light": "ios_light_card", "cover": "ios_cover_card", "lock": "ios_lock_card"}.get(
            dom, "ios_light_card" if is_light(e) else "ios_device_card")
        card = {"type": "custom:button-card", "template": tpl, "entity": eid}
        if dom in ("fan", "climate"):
            card["tap_action"] = {"action": "more-info"}
        cards.append(card)
    return {"type": "grid", "columns": 2, "square": False, "cards": cards}


def build():
    graph = json.loads(GRAPH.read_text())
    coords = json.loads(COORDS.read_text())
    manifest_data = yaml.safe_load(MANIFEST.read_text())["floors"]
    OUT_DIR.mkdir(exist_ok=True)
    for old in OUT_DIR.glob("*.yaml"):
        old.unlink()
    maps, ctrls = {}, {}
    for key, fl in graph["floors"].items():
        m = build_floor(key, fl, coords, manifest_data[key.lower()]["lights"])
        maps[key] = {"label": key, "card": m}
        ctrls[key] = {"label": key, "card": build_controls(key, fl)}
        print(f"{key}: {len(m['elements'])} map elements, base={m['image']}")
    maps["全棟"] = {"label": "全棟", "card": {"type": "picture", "image": "/local/floorplan/3d/floor_all_3d.svg?v=2",
                                              "tap_action": {"action": "none"}}}
    ctrls["全棟"] = {"label": "全棟", "card": {"type": "markdown", "content": "切換到各樓層即可操作該層設備。"}}
    header = "# generated by scripts/generate_floorplan_v4.py - do not edit by hand\n"
    for name, typ, floors in (("map_card", "custom:floorplan-v4-card", maps),
                              ("controls_card", "custom:floorplan-v4-controls", ctrls)):
        body = {"type": typ, "default": "2F", "floors": floors}
        (OUT_DIR / f"{name}.yaml").write_text(
            header + yaml.safe_dump(body, allow_unicode=True, sort_keys=False, width=120))
        print(f"wrote floorplan_v4/{name}.yaml")


def plans():
    """Copy the 2D plan SVGs (without the HA entity layer) to www/floorplan/v4/plans/."""
    import xml.etree.ElementTree as ET

    ET.register_namespace("", "http://www.w3.org/2000/svg")
    graph = json.loads(GRAPH.read_text())
    out = ROOT / "www/floorplan/v4/plans"
    out.mkdir(parents=True, exist_ok=True)
    for key, fl in graph["floors"].items():
        tree = ET.parse(ROOT / "floorplan_src" / fl["svg_file"])
        for parent in list(tree.getroot().iter()):
            for child in list(parent):
                if child.get("id", "").startswith("HA"):
                    parent.remove(child)
        # Safari gives no CSSOM for DOMParser documents, so three.js SVGLoader cannot resolve
        # class="stN" fills there. Inline fill/stroke from the <style> block onto each element.
        ns = "{http://www.w3.org/2000/svg}"
        css = "".join(e.text or "" for e in tree.getroot().iter(ns + "style"))
        rules = {}
        for m in re.finditer(r"([^{}]+)\{([^}]*)\}", css):
            props = dict((k.strip(), v.strip()) for k, v in
                         (d.split(":", 1) for d in m.group(2).split(";") if ":" in d))
            for sel in m.group(1).split(","):
                rules.setdefault(sel.strip().lstrip("."), {}).update(props)
        for el in tree.getroot().iter():
            for cls in (el.get("class") or "").split():
                for prop in ("fill", "stroke", "stroke-width", "fill-rule"):
                    if prop in rules.get(cls, {}) and el.get(prop) is None:
                        el.set(prop, rules[cls][prop])
        dest = out / f"floor_{key.lower()}.svg"
        tree.write(dest, encoding="utf-8", xml_declaration=True)
        print(f"wrote {dest.relative_to(ROOT)}")


DEVICE_DOMAINS = {"light", "switch", "fan", "cover", "lock", "climate", "camera", "media_player"}


def kind_of(e):
    eid, dom = e["entity_id"], e["domain"]
    name = eid.split(".", 1)[1]
    if dom == "sensor":
        if "temperature" in name or "wen_du" in name:
            return "temp"
        if "humidity" in name or "shi_du" in name:
            return "hum"
        if re.search(r"co2|pm2_5|_co$", name):
            return "value"
        if "tesla_wall_connector_status" in name:
            return "charger"
        if re.match(r"(u6_|udm)", name) and name.endswith("_state"):   # UniFi gateway / access points
            return "ap"
        return None
    if dom == "binary_sensor":
        if "person" in name:
            return "person"
        if "motion" in name:
            return "motion"
        if "wei_xian" in name:
            return "safety"
        return None
    if dom == "switch":
        return "switch" if is_light(e) else "plug"
    return dom if dom in DEVICE_DOMAINS else None


def devices(fl):
    out, seen = [], set()
    for e in fl["entities"]:
        eid = e["entity_id"]
        kind = kind_of(e)
        if eid in seen or not kind:
            continue
        seen.add(eid)
        room = re.sub(r"^\dF\s*", "", e.get("room", ""))[:2]
        out.append({"entity": eid, "kind": kind, "x": round(e["coordinates"]["x"], 1),
                    "y": round(e["coordinates"]["y"], 1), "light": is_light(e), "room": room})
    return out


def geometry(svg_name, top_floor=False):
    """Detect stairs, windows and doors in a plan SVG (heuristics on the Illustrator export)."""
    import xml.etree.ElementTree as ET

    ns = "{http://www.w3.org/2000/svg}"
    root = ET.parse(ROOT / "floorplan_src" / svg_name).getroot()
    css = "".join(e.text or "" for e in root.iter(ns + "style"))
    fills = {}
    for m in re.finditer(r"([^{}]+)\{([^}]*)\}", css):
        fm = re.search(r"fill:\s*([^;]+)", m.group(2))
        if fm:
            for sel in m.group(1).split(","):
                fills[sel.strip().lstrip(".")] = fm.group(1).strip().lower()
    stairs, seen = [], set()
    for g in root.iter(ns + "g"):
        if g.get("id", "").startswith("HA"):
            continue
        rects = [c for c in g if c.tag == ns + "rect" and not c.get("transform")]
        paths = [c.get("d", "") for c in g if c.tag == ns + "path"]
        for d in paths:
            vs, hs = re.findall(r"[vV]-?[\d.]+", d), re.findall(r"[hH]-?[\d.]+", d)
            n = max(len(vs), len(hs))
            if not 6 <= n <= 14:
                continue
            for r in rects:
                x, y, w, h = (float(r.get(k, 0)) for k in ("x", "y", "width", "height"))
                if not (55 <= min(w, h) <= 130 and max(w, h) >= 80) or (x, y, w, h) in seen:
                    continue
                seen.add((x, y, w, h))
                # arrow head "M x0,y0 l dx1,dy1 dx2,dy2": its tip shows the walking (up) direction
                tip = None
                for a in paths:
                    m = re.search(r"M([\d.]+),([\d.]+)l(-?[\d.]+)[, ]?(-?[\d.]+)", a)
                    if m:
                        tip = (float(m.group(1)) + float(m.group(3)), float(m.group(2)) + float(m.group(4)))
                run_axis = "x" if w >= h else "y"
                centre = x + w / 2 if run_axis == "x" else y + h / 2
                dirn = 1 if tip is None or (tip[0] if run_axis == "x" else tip[1]) >= centre else -1
                stairs.append({"x": x, "y": y, "w": w, "h": h, "axis": run_axis, "steps": n + 1,
                               "dir": dirn, "h0": 0, "h1": 34})
    # U-shaped staircase: two parallel flights side by side -> first flight 0..17, landing, second 17..34.
    # The southern flight is walked first, which chains the arrows from floor to floor (3F -> 4F -> 5F).
    for a in stairs:
        for b in stairs:
            if a is b or a["axis"] != b["axis"]:
                continue
            if a["axis"] == "x":
                same = abs(a["x"] - b["x"]) < 6 and abs(a["w"] - b["w"]) < 6
                near = -12 <= b["y"] - (a["y"] + a["h"]) < 30
            else:
                same = abs(a["y"] - b["y"]) < 6 and abs(a["h"] - b["h"]) < 6
                near = -12 <= b["x"] - (a["x"] + a["w"]) < 30
            if same and near and a["dir"] != b["dir"]:
                b["h0"], b["h1"], b["landing"] = 0, 17, True
                a["h0"], a["h1"] = 17, 34
    if top_floor:
        for st in stairs:                         # top floor: the staircase goes down through a slab opening
            if st["h0"] == 0 and st["h1"] == 34:
                st["h0"], st["h1"], st["dir"] = 0, -34, -st["dir"]
    openings, centers = [], set()
    for r in root.iter(ns + "rect"):
        if r.get("transform") or fills.get(r.get("class", ""), "#000") != "#fff":
            continue
        x, y, w, h = (float(r.get(k, 0)) for k in ("x", "y", "width", "height"))
        thin, long_ = min(w, h), max(w, h)
        if long_ < 25:
            continue
        kind = "window" if thin <= 1.5 else "door" if 4.5 <= thin <= 5.5 else None
        key = (round(x + w / 2), round(y + h / 2))
        if kind and key not in centers and not any(
                s["x"] <= x <= s["x"] + s["w"] and s["y"] <= y <= s["y"] + s["h"] for s in stairs):
            centers.add(key)
            openings.append({"kind": kind, "x": round(x, 1), "y": round(y, 1), "w": round(w, 1), "h": round(h, 1)})
    return stairs, openings


PEOPLE = [
    {"id": "kenny", "name": "Kenny", "color": "#4fc3f7"},
    {"id": "elay", "name": "Elay", "color": "#f48fb1"},
    {"id": "jerry", "name": "Jerry", "color": "#a5d6a7"},
    {"id": "iris", "name": "Iris", "color": "#ffcc80"},
]
# text from sensor.at_home_<id>_location (helper.yaml) -> floor + point in plan coordinates
LOCATIONS = {
    "車庫": {"floor": "1F", "x": 400, "y": 240},
    "客廳": {"floor": "2F", "x": 360, "y": 300},
    "三樓臥室": {"floor": "3F", "x": 300, "y": 250},
    "四樓Jerry房間": {"floor": "4F", "x": 600, "y": 300},
    "四樓Elay房間": {"floor": "4F", "x": 150, "y": 200},
    "頂樓Kenny房間": {"floor": "5F", "x": 600, "y": 150},
}


FURNITURE = yaml.safe_load((ROOT / "floorplan_src" / "furniture.yaml").read_text()) or {}
# entities that exist in HA but are not in the plan's entity layer
EXTRA_DEVICES = {
    "3F": [{"entity": "sensor.switch_lite_8_poe_state", "kind": "ap", "x": 262.0, "y": 40.0, "light": False}],   # UniFi Switch Lite 8 PoE
    "2F": [{"entity": "sensor.livingroom_homepodmini_temperature", "kind": "temp", "x": 300.0, "y": 200.0, "light": False},
           {"entity": "sensor.livingroom_homepodmini_humidity", "kind": "hum", "x": 300.0, "y": 222.0, "light": False}],
    "5F": [{"entity": "sensor.ricoh_sp_c261sfnw", "kind": "printer", "x": 308.0, "y": 420.0, "light": False},   # printer status + ink levels
           {"entity": "binary_sensor.ding_lou_ding_lou_she_ying_ji_motion", "kind": "motion",
            "x": 676.0, "y": 482.0, "light": False},
           {"entity": "sensor.5f_homepodmini_temperature", "kind": "temp", "x": 393.3, "y": 374.0, "light": False}],
}
# entity layer mistakes in the plan SVG: (floor, wrong id) -> real id
ENTITY_FIX = {("5F", "binary_sensor.che_ku_she_ying_ji_person_detected"): "binary_sensor.wu_lou_she_ying_ji_person_detected",
              # one charger pin: the HomeKit status text sensor (power comes from sensor.tesla_wall_connector_total_power)
              ("1F", "sensor.tesla_wall_connector_status"): "sensor.tesla_charger_homekit_status",
              # 5F: plan reused the 2F kitchen Zigbee plug and the 4F Jerry AP ids
              ("5F", "switch.0x00158d0003923796_plug"): "switch.ding_lou_homepodcha_zuo",
              ("5F", "sensor.u6_iw_4f_jerry_state"): "sensor.u6_iw_5f_kenny_state"}
NAMES = json.loads((ROOT / "floorplan_src" / "entity_names.json").read_text())


OVERRIDES = json.loads((ROOT / "floorplan_src" / "position_overrides.json").read_text()) \
    if (ROOT / "floorplan_src" / "position_overrides.json").exists() else {}


def scene_floors():
    graph = json.loads(GRAPH.read_text())
    floors = {}
    for key, fl in graph["floors"].items():
        vb = fl["viewbox"]
        stairs, openings = geometry(fl["svg_file"], top_floor=key == list(graph["floors"])[-1])
        manual = FURNITURE.get(key, {})
        if manual.get("stairs"):                  # hand-checked flights (role up/down, arrow = up direction)
            stairs = []
            for st in manual["stairs"]:
                up = st["role"] == "up"
                stairs.append({**{k: st[k] for k in ("x", "y", "w", "h", "axis", "steps")},
                               "role": st["role"], "h0": 0, "h1": 34 if up else -34, "badge": st.get("badge", True),
                               "dir": st["arrow"] if up else -st["arrow"]})
        devs = devices(fl)
        # cameras / directional motion sensors drawn with an arrow in the plan: mount point + yaw
        for item in graph.get("cameras", []) + graph.get("directional_sensors", []):
            if item["floor"] != key:
                continue
            kind = "camera" if item["domain"] == "camera" else "motion"
            devs = [d for d in devs if d["entity"] != item["entity_id"]]
            devs.append({"entity": item["entity_id"], "kind": kind, "x": item["mount_point"]["x"],
                         "y": item["mount_point"]["y"], "light": False, "yaw": item["yaw_angle_deg"],
                         "fov": item.get("fov_h_deg", 60)})
        devs += EXTRA_DEVICES.get(key, [])
        # a thin plan line inside a modelled piece of furniture (e.g. the TV drawn on the TV wall) is not a door/window
        boxes = manual.get("furniture", [])
        for w in manual.get("windows", []):          # hand-added glass runs (plan SVG has no window drawn there)
            openings.append({"kind": "window", **{k: float(w[k]) for k in ("x", "y", "w", "h")}})
        openings = [o for o in openings if not any(
            b["x"] <= o["x"] + o["w"] / 2 <= b["x"] + b["w"] and b["y"] <= o["y"] + o["h"] / 2 <= b["y"] + b["h"] for b in boxes)]
        for dr in manual.get("doors", []):
            openings = [o for o in openings if not (o["kind"] == "door" and dr["x"] - 6 <= o["x"] + o["w"] / 2 <= dr["x"] + dr["w"] + 6
                                                    and dr["y"] - 6 <= o["y"] + o["h"] / 2 <= dr["y"] + dr["h"] + 6)]
            devs.append({"entity": dr["entity"], "kind": "doorlock", "x": dr["hinge"][0], "y": dr["y"] + dr["h"] / 2, "light": False})
        for d in devs:
            d["entity"] = ENTITY_FIX.get((key, d["entity"]), d["entity"])
            d["name"] = NAMES.get(d["entity"], "")
            d["src"] = "svg"
            ov = OVERRIDES.get(f"{key}|{d['entity']}")
            if ov:                                   # positions fixed by hand in the 3D card (✎ 調整位置)
                d["x"], d["y"], d["src"] = round(ov[0], 1), round(ov[1], 1), "adjusted"
        zs = manual.get("zones", [])
        for d in devs:
            d["zone"] = next((z["name"] for z in zs if z["x"] <= d["x"] <= z["x"] + z["w"] and z["y"] <= d["y"] <= z["y"] + z["h"]),
                             d.get("room") or key)
        floors[key] = {"label": key, "plan": f"/local/floorplan/v4/plans/floor_{key.lower()}.svg?v=2",
                       "width": vb[2], "height": vb[3], "devices": devs,
                       "stairs": stairs, "openings": openings,
                       "furniture": manual.get("furniture", []), "garage_door": manual.get("garage_door"),
                       "curtains": bool(manual.get("curtains")), "zones": manual.get("zones", []),
                       "scenes": manual.get("scenes", []), "doors": manual.get("doors", []),
                       "floor_color": manual.get("floor_color"), "wall_color": manual.get("wall_color"),
                       "window_frame": manual.get("window_frame"), "window_grille": manual.get("window_grille", []),
                       "wall_colors": manual.get("wall_colors", []), "stair_style": manual.get("stair_style"),
                       "curtain_colors": manual.get("curtain_colors", [])}
    return graph, floors


def build3d():
    graph, floors = scene_floors()
    for key, fl in floors.items():
        print(f"{key}: {len(fl['stairs'])} stairs, {sum(o['kind']=='window' for o in fl['openings'])} windows, "
              f"{sum(o['kind']=='door' for o in fl['openings'])} doors, "
              f"{sum(d['src']=='adjusted' for d in fl['devices'])} adjusted devices")
    for fl in floors.values():                    # entities that do not exist in HA (e.g. duplicate plan markers) are not drawn
        fl["devices"] = [d for d in fl["devices"] if d.get("name")]
    header = "# generated by scripts/generate_floorplan_v4.py - do not edit by hand\n"
    for name, height, tabs in (("map3d_landscape", "calc(100dvh - 88px)", False), ("map3d_portrait", "66vh", True)):
        body = {"type": "custom:floorplan-v4-3d", "default": "2F", "height": height, "tabs": tabs,
                "people": PEOPLE, "locations": LOCATIONS, "floors": floors}
        (OUT_DIR / f"{name}.yaml").write_text(
            header + yaml.safe_dump(body, allow_unicode=True, sort_keys=False, width=120))
        print(f"wrote floorplan_v4/{name}.yaml")


HEIGHT_HINT = {"light": 30, "switch": 24, "plug": 4, "fan": 15, "climate": 30, "camera": 34, "motion": 28, "person": 34,
               "temp": 15, "hum": 15, "value": 15, "safety": 15, "cover": 17, "lock": 12, "media_player": 12, "charger": 18}


def positions():
    """Write the entity position table (YAML / JSON / Markdown) for automations, and sync the scene graph + SVG."""
    graph, floors = scene_floors()
    rows = []
    for key, fl in floors.items():
        lights = [d for d in fl["devices"] if d["kind"] in ("light", "switch") and d["light"] or d["kind"] == "light"]
        clusters = []
        for d in lights:
            c = next((k for k in clusters if k["room"] == d["zone"] and any(
                math.hypot(o["x"] - d["x"], o["y"] - d["y"]) < 110 for o in k["items"])), None)
            if c:
                c["items"].append(d)
            else:
                clusters.append({"room": d["zone"], "items": [d]})
        group_of = {}
        for i, c in enumerate(clusters):
            if len(c["items"]) >= 2:
                for d in c["items"]:
                    group_of[d["entity"]] = f"{key.lower()}_{c['room']}_lights_{i + 1}"
        for d in fl["devices"]:
            zone = d["zone"]
            rows.append({
                "entity_id": d["entity"], "name": d.get("name") or d["entity"], "in_ha": bool(d.get("name")),
                "floor": key, "zone": zone,
                "kind": d["kind"], "x": d["x"], "y": d["y"],
                "world": {"x": round(d["x"] - fl["width"] / 2, 1), "z": round(d["y"] - fl["height"] / 2, 1),
                          "y": HEIGHT_HINT.get(d["kind"], 10)},
                "light_group": group_of.get(d["entity"]),
                "yaw_deg": d.get("yaw"), "source": d["src"],
            })
    meta = {"generated": "2026-10-04", "coordinate_system": "plan px, origin top-left of each floor SVG, +x east, +y south; "
            "world = plan - floor_size/2 (three.js x,z), y = height hint above floor",
            "floor_size": {k: [f["width"], f["height"]] for k, f in floors.items()}}
    (ROOT / "entity_positions.json").write_text(json.dumps({"meta": meta, "entities": rows}, ensure_ascii=False, indent=1))
    (ROOT / "entity_positions.yaml").write_text(
        "# generated by scripts/generate_floorplan_v4.py positions - do not edit by hand\n"
        + yaml.safe_dump({"meta": meta, "entities": rows}, allow_unicode=True, sort_keys=False, width=140))
    md = ["# 實體位置對照表 (ENTITY_POSITIONS)", "",
          "> 由 `scripts/generate_floorplan_v4.py positions` 自動產生。來源：平面圖 SVG 實體圖層 + 使用者在 3D 卡片「✎ 調整位置」存下的修正（`來源=調整`）。",
          "> 座標：每層平面圖像素，原點在左上角，x 向東、y 向南。3D 世界座標 = 平面座標 − 樓層尺寸/2。", "",
          "樓層尺寸：" + "、".join(f"{k} {int(v[0])}×{int(v[1])}" for k, v in meta["floor_size"].items()), ""]
    for key in floors:
        md += [f"## {key}", "", "| 區域 | 名稱 | 實體 | 類型 | x | y | 燈群組 | 來源 |", "|---|---|---|---|---|---|---|---|"]
        for r in sorted((r for r in rows if r["floor"] == key), key=lambda r: (r["zone"], r["kind"], r["x"])):
            md.append(f"| {r['zone']} | {r['name']} | `{r['entity_id']}` | {r['kind']} | {r['x']} | {r['y']} | "
                      f"{r['light_group'] or ''} | {'調整' if r['source'] == 'adjusted' else '原圖'}{'' if r['in_ha'] else ' ⚠HA無此實體'} |")
        md.append("")
    (ROOT / "ENTITY_POSITIONS.md").write_text("\n".join(md) + "\n")
    # keep the scene graph and SVG entity layer in sync with the adjusted positions
    n_graph = n_svg = 0
    for key, fl in graph["floors"].items():
        for e in fl["entities"]:
            ov = OVERRIDES.get(f"{key}|{e['entity_id']}")
            if ov:
                e["coordinates"] = {"x": ov[0], "y": ov[1]}; n_graph += 1
    GRAPH.write_text(json.dumps(graph, ensure_ascii=False, indent=2))
    for key, fl in graph["floors"].items():
        path = ROOT / "floorplan_src" / fl["svg_file"]
        txt = path.read_text()
        for k, ov in OVERRIDES.items():
            f, eid = k.split("|")
            if f != key:
                continue
            esc = eid.replace("_", "_x5F_")
            pat = re.compile(r'(<circle id="' + re.escape(esc) + r'"[^>]*?)cx="[^"]*" cy="[^"]*"')
            txt, n = pat.subn(lambda m: f'{m.group(1)}cx="{ov[0]}" cy="{ov[1]}"', txt)
            n_svg += n
        path.write_text(txt)
    print(f"wrote entity_positions.yaml/.json, ENTITY_POSITIONS.md ({len(rows)} entities); "
          f"synced {n_graph} scene-graph entries and {n_svg} SVG circles")


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "manifest"
    if cmd == "manifest":
        manifest()
    elif cmd == "build":
        build()
        build3d()
    elif cmd == "plans":
        plans()
    elif cmd == "build3d":
        build3d()
    elif cmd == "positions":
        positions()
    else:
        sys.exit(f"unknown command: {cmd}")
