### AI Configuration V1.0 ###

homeassistant:
  packages: !include_dir_named packages
  
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
# Text to speech
tts:
  - platform: google_translate
    language: 'zh-tw'
#  - platform: edge_tts
#    language: zh-TW # Default language or voice (Optional)
group: !include groups.yaml
automation: !include automations.yaml
automation ai_managed: !include_dir_merge_list Automations
script: !include scripts.yaml
script ai_managed: !include_dir_merge_named Scripts
scene: !include scenes.yaml
sensor: !include sensors.yaml
frontend:
  themes: !include_dir_merge_named themes

recorder: 
  commit_interval: 10
  purge_keep_days: 180
  
#####google home
google_assistant:
  project_id: fluid-etching-332006
  service_account: !include google_assistant.json
  report_state: true
  expose_by_default: false
  entity_config:
    

#homekit:
#  - name: HA Family 3
#    port: 21105
#    ip_address: 192.168.68.73
#    advertise_ip: 192.168.68.73
#    filter:
#      include_domains:
#        - light
#recorder:
#	purge_interval: 
#	purge_keep_days: 365
#homeassistant:
#  external_url: https://jnas916p.synology.me:8124
#  internal_url: http://192.168.68.73:8123
#http:
#  ssl_certificate: /config/ssl/cert.pem
#  ssl_key: /config/ssl/privkey.pem
#  base_url: https://jnas916p.synology.me
#  cors_allowed_origins:
#    - https://jnas916p.synology.me
 #   - http://192.168.68.73
#  ssl_chain: /config/ssl/chain.pem
fan:
  - platform: xiaomi_miio_fan
    name: 客廳電風扇      #名稱
    host: 192.168.68.60    #IP
    token: 9854d3850030fe5d75eabce4f878cfd0  #自己的token
    preset_modes_override: []     #讓homekit的按鍵顯示正常
    model: zhimi.fan.sa1 #自己的電風扇model

http:
  use_x_forwarded_for: true
  server_port: 8125
  trusted_proxies:
    - 127.0.0.1           # Loopback
    - 192.168.68.0/24     # 本地網路
    - 127.30.32.0/24      # Docker/Supervisor 網路
    - 127.17.0.0/24       # Docker/Supervisor 網路
    - 211.79.170.9        # 外部 IP, 請確認這是可信賴的反向代理
  ip_ban_enabled: true
###
###

notify:                      #若已有設定其他notify組件則不須輸入此行
  - name: line_notification_group  #可修改成你要的名稱 ＃不建議使用中文
    platform: notify_line
    access_token: 'a9L8vnbBdqbne74GbBq2MdKIgFFu686EzbXOCuSYnq6'  #將前面步驟取得的權杖輸入於此
  - name: line_bot_chiangfamilygroup
    platform: line_bot
    client_id: 'C26ff4e9d30159ba5264a1676f46f8f86'
    access_token: 'tVQIJ4UIbOsl5n5BAAQMpjYSMDg2jlb7brjoffYPeB8CU+MYYJxcPXA9x1Ka1ze+9XkmvahZMQtvV07NJCm7nBkGc8fzzUlY7uHvr8Gnc/2a/e8jqkdjUNwIsdCYD6skWqngM1GtbDxboIevIbN4OwdB04t89/1O/w1cDnyilFU='
  
  
lovelace:
  mode: storage #use ui-lovelace.yaml
  resources: #hacs
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/swipe-card/swipe-card.js
      type: module
    - url: /hacsfiles/Homekit-panel-card/homekit-panel-card.js
      type: module
    - url: /browser_mod.js
      type: module
    - url: /hacsfiles/light-popup-card/light-popup-card.js
      type: module
    - url: /community_plugin/thermostat-popup-card/thermostat-popup-card.js
      type: module
    - url: /community_plugin/media_player-popup-card/media_player-popup-card.js
      type: module
    - url: /hacsfiles/sidebar-card/sidebar-card.js
      type: module  
    - url: /local/mini-graph-card-bundle.js?v=0.11.0
      type: module
    - url: /community_plugin/cover-popup-card/cover-popup-card.js
      type: module
    - url: /community_plugin/switch-popup-card/switch-popup-card.js
      type: module  
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: 家庭中心Beta
      icon: mdi:home
      show_in_sidebar: true    
      filename: new-ui.yaml
