# Deprecated UI automations backup (migrated out of configuration/automations.yaml)
- id: '1683863915571'
  alias: 12客廳電視自動化
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: fdcccfa405461070717b80a56a590960
    entity_id: remote.sony_bravia_tv
    domain: remote
    for:
      hours: 0
      minutes: 0
      seconds: 0
  - platform: state
    entity_id:
    - media_player.sony_bravia_tv
    attribute: media_title
    to: HDMI 1
    for:
      hours: 0
      minutes: 0
      seconds: 2
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: media_player.sony_bravia_tv
      attribute: media_title
      state: TATV-8000
      enabled: false
    - condition: state
      entity_id: media_player.sony_bravia_tv
      attribute: media_title
      state: HDMI 1
  action:
  - service: remote.send_command
    data:
      command: Confirm
    target:
      device_id: fdcccfa405461070717b80a56a590960
    enabled: false
  - delay:
      hours: 0
      minutes: 0
      seconds: 8
      milliseconds: 0
    enabled: false
  - service: remote.send_command
    data:
      command: Hdmi1
    target:
      device_id: fdcccfa405461070717b80a56a590960
    enabled: false
  - delay:
      hours: 0
      minutes: 0
      seconds: 8
      milliseconds: 0
    enabled: false
  - service: remote.send_command
    data:
      command: Confirm
    target:
      device_id: fdcccfa405461070717b80a56a590960
    enabled: false
  - service: remote.send_command
    data:
      command: Hdmi1
    target:
      device_id: fdcccfa405461070717b80a56a590960
    enabled: false
  - delay:
      hours: 0
      minutes: 0
      seconds: 6
      milliseconds: 0
    enabled: false
  - service: remote.send_command
    data:
      command: Hdmi1
    target:
      device_id: fdcccfa405461070717b80a56a590960
    enabled: false
  - repeat:
      until:
      - condition: state
        entity_id: media_player.sony_bravia_tv
        attribute: media_title
        state: TATV-8000
      sequence:
      - service: remote.send_command
        data:
          command: Hdmi1
        target:
          device_id: fdcccfa405461070717b80a56a590960
      - delay:
          hours: 0
          minutes: 0
          seconds: 1
          milliseconds: 0
  - service: remote.send_command
    data:
      command: Confirm
    target:
      device_id: fdcccfa405461070717b80a56a590960
    enabled: true
  mode: single
- id: '1684559573269'
  alias: 13遙控器轉台
  description: ''
  trigger: []
  condition: []
  action:
  - service: remote.send_command
    data:
      delay_secs: 0.4
      hold_secs: 0
      command: Num5
    target:
      device_id: fdcccfa405461070717b80a56a590960
  - service: remote.send_command
    data:
      hold_secs: 0
      command: Num1
      delay_secs: 0.4
    target:
      device_id: fdcccfa405461070717b80a56a590960
  mode: single